// Do not modify this file, it was generated by _scripts/gen-asset-components.ts

/* eslint-disable jsx-a11y/alt-text */

import { mergeClassAndStyleProps } from "@/shared";
import Image, { ImageProps } from "next/image";
import React from "react";

export const ImageDarkIllustration: React.FC<Omit<ImageProps, "src">> = (props) => {
  return mergeClassAndStyleProps(
    props, 
    <Image src={"/assets/images/dark-illustration.png"} {...props}/>
  );
};

export const imageDarkIllustrationSrc = "/assets/images/dark-illustration.png";