version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - ./.build/postgresql-data:/var/lib/postgresql/data
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
